apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  name: rajattyagiin-pa-recurrent-nattydatetime
spec:
  description: Imported application for rajattyagiin/pa-recurrent-nattydatetime
  org: rajattyagiin
  provider: https://github.com
  providerName: github
  repo: pa-recurrent-nattydatetime
  scheduler:
    kind: ""
    name: ""
