adminUser:
  password: local:tagscloudab-tagscluster/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  token: local:tagscloudab-tagscluster/pipelineUser:token
  username: rajattyagius
prow:
  hmacToken: local:tagscloudab-tagscluster/prow:hmacToken
